Repository our-exhibition-is-open/BE-3dinterest, pull requests merged in 2023-11, with the labels that each got.

#3 회원가입 페이지 백앤드 개발
  build.gradle
  src/main/java/com/team2/_3dinterest/domain/seunghun/SecurityConfig.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/Login.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/LoginController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/UserController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/service/UserService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/service/keep
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/SiteUser.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/UserCreateForm.java
Labels: Feature

#4 로그인/로그아웃 페이지 백앤드 개발
  src/main/java/com/team2/_3dinterest/domain/seunghun/SecurityConfig.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/UserController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/service/UserSecurityService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/UserRole.java
Labels: Feature

#6 /api/users/{username}/details로 요청을 보내면 해당 유저의 상세 정보를 받고, /api/users/{username}/files로 요청을 보내면 해당 유저가 업로드한 파일 목록을 받는 api 추가
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/UserApiController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/UserController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/FileDetailDTO.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserDetailsDTO.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/SiteUser.java
Labels: bug, Feature

#8 /api/users/{username}/files/{fileId}를 통해 파일 상세 정보를 조회하는 API
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/UserApiController.java
Labels: Feature

#9 /mypage api 추가, FileDetail에 annotation추가, UderFile Entitiy 추가
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/MyPageController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserFileRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/UserFile.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/dto/FileDetail.java
Labels: bug, Feature

#10 [Refactor] 파일 업로드 로직 변경 및 JPA 추가
  build.gradle
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/AmazonS3ResourceStorage.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/controller/UploadController.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/dto/RequestUploadDto.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/dto/ResponseFileDto.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/entity/UploadEntity.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/repository/UploadRepository.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/service/FileUploadService.java
  src/main/java/com/team2/_3dinterest/global/util/MultipartUtil.java
Labels: Refactor

#13 /files/byParentID 입력시
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/MyPageController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserFileRepository.java
Labels: bug, Feature

#17 db에 맞게 재설계 및 parentID를 공유하는 postID를 조회하는 기능 구현
  build.gradle
  src/main/java/com/team2/_3dinterest/domain/seunghun/File/FileEntity.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/File/FileEntityRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/File/FileService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/MyPageController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/UserApiController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/FileDetailDTO.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/FileDetailRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/ResponseFileDto.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserDetailsDTO.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserEntityDTO.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserFileRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/service/UserSecurityService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/service/UserService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/SiteUser.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/UserEntity.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/UserFile.java
Labels: bug, Feature

#18 [Refactor] 업로드 정보 toEntity를 통해 변환하도록 변경
  build.gradle
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/controller/UploadController.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/dto/RequestUploadDto.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/dto/ResponseFileDto.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/entity/UploadEntity.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/s3/AmazonS3ResourceStorage.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/service/FileUploadService.java
  src/main/java/com/team2/_3dinterest/global/util/MultipartUtil.java
Labels: Refactor
