Repository our-exhibition-is-open/BE-3dinterest, pull requests merged in 2023-12, with the labels that each got.

#19 [Feature] 다운로드 구현
  src/main/java/com/team2/_3dinterest/domain/yugyeong/download/controller/DownloadController.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/download/dto/RequestDownloadDto.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/download/service/DownloadService.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/entity/DownloadEntity.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/entity/PostEntity.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/repository/DownloadRepository.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/repository/PostRepository.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/controller/UploadController.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/dto/ResponseUploadDto.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/repository/UploadRepository.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/upload/service/UploadService.java
  src/main/java/com/team2/_3dinterest/global/common/s3/AmazonS3ResourceStorage.java
  src/main/java/com/team2/_3dinterest/global/common/s3/S3Download.java
  src/main/java/com/team2/_3dinterest/global/config/WebConfig.java
  src/main/java/com/team2/_3dinterest/global/util/MultipartUtil.java
Labels: Feature

#21 각종 오류 수정 및 db연동 문제 최종 해결
  src/main/java/com/team2/_3dinterest/domain/seunghun/File/FileEntityRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/File/FileService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/controller/MyPageController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/ResponseFileDto.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserEntityDTO.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserFileRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/service/UserSecurityService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/SiteUser.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/UserEntity.java
Labels: bug

#23 [Feature] 전체 게시물 목록 조회 구현
  src/main/java/com/team2/_3dinterest/domain/yugyeong/postlist/controller/PostListController.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/postlist/service/PostListService.java
  src/main/java/com/team2/_3dinterest/domain/yugyeong/repository/PostRepository.java
Labels: Feature

#26 [Refactor]
  src/main/java/com/team2/_3dinterest/domain/yugyeong/download/service/DownloadService.java
Labels: Refactor

#29 [Refactor] 좋아요 기능의 오류를 수정한다.
  src/main/java/com/team2/_3dinterest/domain/ahyeon/heart/HeartEntity.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/Post.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/controller/PostController.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/dto/PostDto.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/entity/PostEnti.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostService.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostServiceImpl.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/user/User.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/user/UserEnti.java
Labels: Refactor

#30 [Refactor] 업데이트된 기능을 데이터베이스에 저장한다.
  src/main/java/com/team2/_3dinterest/domain/ahyeon/heart/Heart.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/heart/HeartEntity.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/heart/HeartRepository.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/Post.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/PostRepo.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/controller/PostController.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/dto/PostDto.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/entity/PostEnti.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostService.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostServiceImpl.java
Labels: Refactor

#31 [Bug] 자료형 에러 버그를 고친다
  src/main/java/com/team2/_3dinterest/domain/ahyeon/heart/Heart.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/heart/HeartEntity.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/Post.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/PostRepo.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/controller/PostController.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/dto/PostDto.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/entity/PostEnti.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostService.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostServiceImpl.java
Labels: bug

#32 [Refactor] 패키지 이름을 like로 수정한다.
  src/main/java/com/team2/_3dinterest/domain/ahyeon/heart/HeartRepository.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/controller/LikeController.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/dto/GetPostDto.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/dto/LikeDto.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/dto/PostDto.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/entity/LikeEntity.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/entity/Post_Entity.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/repository/HeartRepository.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/repository/Post_Repository.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/service/PostInterface.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/like/service/PostService.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/controller/PostController.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostService.java
  src/main/java/com/team2/_3dinterest/domain/ahyeon/post/service/PostServiceImpl.java
Labels: Refactor

#33 [Bug]패키지 위치 수정 및 각종 오류 수정(진행중)
  src/main/java/com/team2/_3dinterest/domain/seunghun/File/FileEntityRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/entity/ContributeEntity.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/entity/FileEntity.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/entity/UserEntity.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/mypage/controller/MyPageController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/mypage/dto/ResponseFileDto.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/mypage/dto/UserEntityDTO.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/mypage/service/FileService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/FileEntityRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/repository/UserFileRepository.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/security/SecurityConfig.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/security/UserRole.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/security/UserSecurityService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/controller/UserApiController.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/sevice/UserCreateService.java
  src/main/java/com/team2/_3dinterest/domain/seunghun/user/sevice/UserService.java
Labels: bug

#36 [Refactor]db에 맞게 데이터 타입 수정
  src/main/java/com/team2/_3dinterest/domain/seunghun/entity/FileEntity.java
Labels: Refactor
